Repository redhat-cop/infra-ansible, pull requests merged in 2018-03, with the labels that each got.

#146 email send
  roles/email/send/README.md
  roles/email/send/tasks/mailit.yml
  roles/email/send/tasks/main.yml
  roles/email/send/tests/inventory/group_vars/all.yml
  roles/email/send/tests/playbook.yml
  roles/email/send/tests/roles
Labels: new feature

#153 Fixing bastion playbook based on role move
  inventory/bastion/group_vars/bastion.yml
  playbooks/provision-bastion/README.md
  playbooks/provision-bastion/install.yml
  playbooks/provision-bastion/inventory/group_vars/bastion.yml
  playbooks/provision-bastion/inventory/group_vars/centos.yml
  playbooks/provision-bastion/inventory/group_vars/fedora.yml
  playbooks/provision-bastion/inventory/hosts
Labels: bug

#154 Updating the 'update-host' role to allow greater flexibility
  roles/update-host/README.md
  roles/update-host/tasks/main.yml
  roles/update-host/tasks/reboot-host.yml
  roles/update-host/tasks/update-host.yml
  roles/update-host/tasks/wait-for-host.yml
Labels: enhancement
