Repository redhat-cop/infra-ansible, pull requests merged in 2020-05, with the labels that each got.

#447 Generate csr python3
  roles/certs/generate-csr/library/generate_csr.py
Labels: enhancement

#448 Fixing dns zone role to avoid clobbering existing tsig keys
  roles/dns/config-dns-server-bind/files/named.conf
  roles/dns/config-dns-server-bind/handlers/main.yml
  roles/dns/config-dns-server-bind/tasks/restart_named.yml
  roles/dns/manage-dns-zones-bind/tasks/generate_keys.yml
  roles/dns/manage-dns-zones-bind/tasks/keys.yml
  roles/dns/manage-dns-zones-bind/templates/domain-key.j2
  roles/dns/manage-dns-zones-bind/templates/list-tsig-keys.j2
  roles/dns/manage-dns-zones-bind/templates/tsig-key.j2
Labels: bug

#449 Adding automation to provision and configure Red Hat Single Sign-On
  inventory/rh-sso/group_vars/all.yml
  inventory/rh-sso/group_vars/osp-provisioner.yml
  inventory/rh-sso/group_vars/rh-sso-hosts.yml
  inventory/rh-sso/host_vars/localhost.yml
  inventory/rh-sso/hosts
  inventory/rh-sso/openstack.py
  playbooks/provision-rh-sso/README.md
  playbooks/provision-rh-sso/deploy-rh-sso.yml
  playbooks/provision-rh-sso/main.yml
  playbooks/provision-rh-sso/roles
  roles/config-rh-sso/README.md
  roles/config-rh-sso/defaults/main.yml
  roles/config-rh-sso/tasks/configure-rh-sso.yml
  roles/config-rh-sso/tasks/main.yml
  roles/config-rh-sso/tasks/prereq.yml
  roles/config-rh-sso/tasks/setup-rh-sso.yml
  roles/config-rh-sso/templates/realm.json.j2
Labels: enhancement, new feature
