Repository redhat-cop/infra-ansible, pull requests merged in 2021-08, with the labels that each got.

#636 Ansible Tower: Update manage-inventories
  roles/ansible/tower/manage-inventories/tasks/main.yml
  roles/ansible/tower/manage-inventories/tasks/process-inventory.yml
Labels: enhancement

#632 Ansible Tower: Fix missing organization_id
  roles/ansible/tower/manage-organizations/tasks/process-organization.yml
Labels: bug

#637 Updated to allow for automatic notifications of AWS onboarding
  roles/identity-management/manage-aws-identities/filter_plugins/set-aws-user-flags.py
  roles/identity-management/manage-aws-identities/tasks/create_users.yml
  roles/identity-management/populate-users/tasks/main.yml
  roles/notifications/send-email/tasks/main.yml
Labels: enhancement

#638 Adding 'pandoc' to infra-ansible container image
  images/infra-ansible/Dockerfile
Labels: enhancement

#639 Add AWS CLI to the container image
  images/infra-ansible/Dockerfile
Labels: enhancement, new feature

#640 Making 'aws_profile' optional to make password assingment work without
  roles/identity-management/manage-aws-user-password/README.md
  roles/identity-management/manage-aws-user-password/tasks/main.yml
Labels: enhancement

#641 Generate password parameters for customizing strength of password
  roles/identity-management/manage-user-password/defaults/main.yml
  roles/identity-management/manage-user-password/tasks/generate-password.yml
Labels: enhancement

#642 Eliminating some of the no_log flags
  roles/ansible/tower/config-ansible-tower-ocp/tasks/openshift_authenticate.yml
Labels: enhancement
