Repository redhat-cop/infra-ansible, pull requests merged in 2021-05, with the labels that each got.

#610 Fix kustomize permissions in infra-ansible Dockerfile
  images/infra-ansible/Dockerfile
Labels: bug

#611 config-ansible-ocp: Added missing option to skip TLS verification on one of OC calls
  roles/ansible/tower/config-ansible-tower-ocp/tasks/openshift_authenticate.yml
Labels: bug

#612 Add dependabot for github actions
  .github/dependabot.yaml
  files/openstack.yml
Labels: enhancement, new feature

#613 Add tower job launch role
  playbooks/ansible/tower/configure-ansible-tower.yml
  roles/ansible/tower/launch-tower-jobs/README.md
  roles/ansible/tower/launch-tower-jobs/defaults/main.yml
  roles/ansible/tower/launch-tower-jobs/filter_plugins
  roles/ansible/tower/launch-tower-jobs/library
  roles/ansible/tower/launch-tower-jobs/tasks/launch-job.yml
  roles/ansible/tower/launch-tower-jobs/tasks/main.yml
  roles/ansible/tower/launch-tower-jobs/templates/launch-job-template.j2
  roles/ansible/tower/launch-tower-jobs/tests/main.yml
  roles/ansible/tower/manage-job-templates/templates/job-template.j2
  roles/ansible/tower/manage-workflow-templates/README.md
  roles/ansible/tower/manage-workflow-templates/tasks/process-workflow-node.yml
  roles/ansible/tower/manage-workflow-templates/templates/workflow-template.j2
Labels: enhancement, new feature

#618 Adding functionality to 'config-packages' to remove packages
  roles/config-packages/tasks/packages.yml
  roles/config-packages/tasks/rhelpackages.yml
Labels: enhancement, new feature

#619 Update schedule_utils filter plugin to use timezone with rrule
  filter_plugins/schedule_utils.py
  roles/ansible/tower/launch-tower-jobs/tasks/main.yml
Labels: enhancement
