Repository redhat-cop/infra-ansible, pull requests merged in 2021-04, with the labels that each got.

#600 Fix string/bool type mismatch on pg_emptydir check
  roles/ansible/tower/config-ansible-tower-ocp/tasks/precheck.yml
  roles/ansible/tower/config-ansible-tower-ocp/tasks/setup_pvc.yml
Labels: bug

#601 Locking in 'pip' to earlier version to band-aid build issue
  images/infra-ansible/Dockerfile
Labels: bug

#602 Fixes for Tower on OCP vs Tower non-containerized deployments
  roles/ansible/tower/config-ansible-tower-ldap/tasks/ldap.yml
  roles/ansible/tower/config-ansible-tower-ocp/tasks/setup_pvc.yml
Labels: bug

#603 Container image with Python3
  files/openstack_inventory.py
  images/infra-ansible/Dockerfile
  images/infra-ansible/README.md
  images/infra-ansible/root/usr/local/bin/ep
  inventory/ansible-tower/openstack.py
  inventory/ansible-tower/openstack_inventory.py
  inventory/bastion/openstack.py
  inventory/bastion/openstack_inventory.py
  inventory/dns-server/openstack.py
  inventory/dns-server/openstack_inventory.py
  inventory/idm-server/openstack.py
  inventory/idm-server/openstack_inventory.py
  inventory/minishift-remote/openstack.py
  inventory/minishift-remote/openstack_inventory.py
  inventory/nfs-server/openstack.py
  inventory/nfs-server/openstack_inventory.py
  inventory/rh-sso/openstack.py
  inventory/rh-sso/openstack_inventory.py
  inventory/satellite-server/openstack.py
  inventory/satellite-server/openstack_inventory.py
  playbooks/osp/inventory/openstack.py
  playbooks/osp/inventory/openstack_inventory.py
  roles/osp/admin-sec-group/test/inventory/old/openstack.py
Labels: new feature

#604 Eliminating prereq tasks for OSP roles
  roles/osp/admin-floating-ip/tasks/main.yml
  roles/osp/admin-image/README.md
  roles/osp/admin-image/tasks/main.yml
  roles/osp/admin-instance/tasks/main.yml
  roles/osp/admin-network/tasks/main.yml
  roles/osp/admin-nova-flavor/README.md
  roles/osp/admin-nova-flavor/tasks/main.yml
  roles/osp/admin-project/tasks/main.yml
  roles/osp/admin-sec-group/tasks/main.yml
  roles/osp/admin-user/tasks/main.yml
  roles/osp/admin-volume/tasks/main.yml
Labels: enhancement

#605 Quay Prototype support
  roles/scm/quay/README.md
  roles/scm/quay/tasks/manage_organization.yml
  roles/scm/quay/tasks/manage_prototypes.yml
Labels: enhancement

#606 Configure Ansible Tower Organization role
  playbooks/ansible/tower/configure-ansible-tower.yml
  roles/ansible/tower/manage-organizations/README.md
  roles/ansible/tower/manage-organizations/defaults/main.yml
  roles/ansible/tower/manage-organizations/filter_plugins
  roles/ansible/tower/manage-organizations/library
  roles/ansible/tower/manage-organizations/tasks/main.yml
  roles/ansible/tower/manage-organizations/tasks/process-galaxy-credentials.yml
  roles/ansible/tower/manage-organizations/tasks/process-organization.yml
  roles/ansible/tower/manage-organizations/templates/associate_galaxy_credential.j2
  roles/ansible/tower/manage-organizations/templates/galaxy_credential.j2
  roles/ansible/tower/manage-organizations/templates/organization.j2
  roles/ansible/tower/manage-organizations/tests/inventory/group_vars/tower.yml
  roles/ansible/tower/manage-organizations/tests/inventory/hosts
  roles/ansible/tower/manage-organizations/tests/roles
  roles/ansible/tower/manage-organizations/tests/test.yml
Labels: new feature

#607 Infra-ansible docker image updates and compability changes
  files/openstack.yml
  images/infra-ansible/Dockerfile
  roles/ansible/tower/library/rest_get.py
  roles/certs/generate-csr/library/generate_csr.py
Labels: enhancement
